### ISSUE TITLE
pkg-resources not exist

### ISSUE THREAD

**Issue by DevDorrejo** [phreakyphoenix/WhastAppBulkMessager#5]
hello, i do pip install -r requirements.txt and pkg-resources not exist on the pip repo

ERROR: Could not find a version that satisfies the requirement pkg-resources==0.0.0 (from -r requirements.txt (line 7)) (from versions: none)
ERROR: No matching distribution found for pkg-resources==0.0.0 (from -r requirements.txt (line 7))

**Comment by phreakyphoenix** [comment]
Please check out this link https://stackoverflow.com/questions/7446187/no-module-named-pkg-resources
TLDR;  pip install setuptools or 
sudo apt-get install --reinstall python-pkg-resources or 
sudo apt-get install --reinstall python-setuptools

Closing as it's more of an isolated dependency issue, and not an intrinsic error in the code from this repo. But feel free to ask in this thread if your issue persists.
