### ISSUE TITLE
Line 49: print (f'Sent to {index} : {number}')

### ISSUE THREAD

**Issue by salimcansatici** [phreakyphoenix/WhastAppBulkMessager#8]
Hi,

I am got the below error

```
File "run.py", line 49
    print (f'Sent to {index} : {number}')
                                       ^
SyntaxError: invalid syntax
```

**Comment by phreakyphoenix** [comment]
Please use python 3.8 or above, 
else replace with 
print ('Sent to '+str(index)+' : '+str(number))
similarly replace remaining occurrences of f-strings in other print statements too.
