### ISSUE TITLE
Doesn't send the message 

### ISSUE THREAD

**Issue by burraksumer** [phreakyphoenix/WhastAppBulkMessager#9]
Hi, this is a great piece of software!

I've actually checked the CSS selector and played with it a few times yet I couldn't get it to send the message. It is writing the message and also refreshes the page if I wait enough but does not send it, doesn't hit the enter key for some reason. 

Trying to solve the problem but please let me know if you know the solution!

**Comment by phreakyphoenix** [comment]
Please let us know if you changed any other parameters. To debug, try increasing TRIES to 50 if you're on a slow network.

The enter key is pressed by the line:
`driver.find_element_by_css_selector(css_selector).send_keys(Keys.RETURN)`

Try debugging by whether that line works in other contexts like whether you can do a selenium-powered google search with a search query and pressing the enter key. 

If it's still unresolved, feel free to reopen the issue and add your selenium version and operating system and browser details and I'll try to look into it.
